usecase-beta
direction LR
actor Admin("Admin")
actor acteur("acteur")
actor visisteur("visisteur")

systemBoundary "blog"
  Checkout("Consulter les catégories")
  ajoute("Ajouter une catégorie")
  mod("Modifier une catégorie")
  sup("Supprimer une catégorie")
  cre("Créer un auteur")
  valider("Valider un article")
  pub("Publier un article")

  aj("Ajouter un article")
  Modifier("Modifier un article non publié")
  spu("Supprimer un article non publié")
  change("Changer son profil")

  cons("Consulter les articles")



end
Admin -- Checkout
Admin -- ajoute
Admin -- mod
Admin -- sup
Admin -- cre
Admin -- pub
Admin -- valider
acteur -- aj
acteur -- Modifier
acteur -- spu
acteur -- change
visisteur -- cons

